language: python
python:
- "3.3"
- "3.4"
# command to install dependencies
install:
- pip install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package=singleton_factory
after_success:
- coveralls
